language: node_js
node_js:
  - stable

branches:
    except:
      - gh-pages

script:
    - ng build --prod --output-path docs --base-href /daywriting-v2/

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master  # branch: develop
    local_dir: docs
